---
title: "bureau"
output: html_document
date: "2025-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bureau

this is where i am going to work on all of that stuff and whatnot, which 
might be cool and things

bringing in the data 

```{r}
library(tidyverse)
library(dplyr)
library(tidymodels)
library(discrim)
library(LiblineaR)

source(here::here("data_cleaning.R"))
source(here::here("functions.R"))
source(here::here("splits.R"))
```


```{r}
all_bureau <- read_csv(here::here("Data", "bureau.csv"))
head(all_bureau)
# DAYS_CREDIT
# COUNT() of all the observations and whatnot
```

```{r}
bureau_grouped <- all_bureau %>%
  group_by(SK_ID_CURR) %>%
  summarise(
    NUM_CREDITS = n(), 
    MEAN_DAYS_CREDIT = round(mean(abs(DAYS_CREDIT), na.rm = TRUE), 2)
  )

head(bureau_grouped)
```

```{r}
# load dataframe
all_credit <- read_csv(here::here("Data", "application_train.csv"))

# for determining income categories

bottom <- 100000
middle <- 150000
top <- 250000


# option 1
# aggregate documents flagged, one-hot-encode, and select columns
# NOTE: some parts commented out to prevent collinearity
credit <- all_credit %>%
  mutate(TARGET = factor(TARGET, levels = c(0, 1))) %>%
  mutate(
    DOCUMENTS_FLAGGED = rowSums(dplyr::select(., starts_with("FLAG_DOCUMENT"))),
    DAYS_BIRTH = abs(DAYS_BIRTH)
  ) %>%
  mutate(
    CONTRACT_TYPE_CASH = ifelse(NAME_CONTRACT_TYPE=="Cash loans", 1, 0),
    CONTRACT_TYPE_REVOLVING = ifelse(NAME_CONTRACT_TYPE=="Revolving loans", 1, 0),
    EDUCATION_TYPE_SECONDARY = ifelse(NAME_EDUCATION_TYPE=="Secondary / secondary special", 1, 0),
    EDUCATION_TYPE_HIGHER = ifelse(NAME_EDUCATION_TYPE=="Higher education", 1, 0),
    FAMILY_STATUS_MARRIED = ifelse(NAME_FAMILY_STATUS=="Married", 1, 0),
    FAMILY_STATUS_OTHER = ifelse(!NAME_FAMILY_STATUS %in% c("Married", "Single / not married"), 1, 0),
    HOUSING_TYPE_OWN = ifelse(NAME_HOUSING_TYPE=="House / apartment", 1, 0),
    HOUSING_TYPE_PARENTS = ifelse(NAME_HOUSING_TYPE=="With parents", 1, 0),
    FLAG_OWN_CAR = ifelse(FLAG_OWN_CAR =="Y", 1, 0),
    FLAG_OWN_REALTY = ifelse(FLAG_OWN_REALTY=="Y", 1, 0)#,
    #CODE_GENDER = ifelse(CODE_GENDER=="F", 1, 0)
  ) %>%
    mutate(
    INCOME_CATEGORY = case_when(
      AMT_INCOME_TOTAL < bottom ~ "FOURTH", 
      AMT_INCOME_TOTAL > bottom & AMT_INCOME_TOTAL <= middle ~ "THIRD", 
      AMT_INCOME_TOTAL > middle & AMT_INCOME_TOTAL <= top ~ "SECOND", 
      AMT_INCOME_TOTAL > top ~ "FIRST"
    )
  ) %>% 
   mutate(
    INCOME_CLASS_FOURTH = ifelse(INCOME_CATEGORY == "FOURTH", 1, 0), 
    INCOME_CLASS_THIRD = ifelse(INCOME_CATEGORY == "THIRD", 1, 0),
    INCOME_CLASS_SECOND = ifelse(INCOME_CATEGORY == "SECOND", 1, 0),
    INCOME_CLASS_FIRST = ifelse(INCOME_CATEGORY == "FIRST", 1, 0)
  ) %>%
  dplyr::select(
    SK_ID_CURR,
    CONTRACT_TYPE_REVOLVING,
    FLAG_OWN_CAR,
    FLAG_OWN_REALTY,
    CNT_CHILDREN,
    AMT_INCOME_TOTAL,
    AMT_CREDIT,
    AMT_ANNUITY,
    AMT_GOODS_PRICE,
    EDUCATION_TYPE_SECONDARY,
    EDUCATION_TYPE_HIGHER,
    FAMILY_STATUS_MARRIED,
    FAMILY_STATUS_OTHER,
    HOUSING_TYPE_OWN,
    HOUSING_TYPE_PARENTS,
    DAYS_EMPLOYED,
    DOCUMENTS_FLAGGED,
    INCOME_CLASS_FOURTH,
    INCOME_CLASS_THIRD, 
    INCOME_CLASS_SECOND,
    REGION_POPULATION_RELATIVE,
    CODE_GENDER,
    TARGET
  )

quantile_25 <- as.numeric(quantile(credit$AMT_INCOME_TOTAL)[2])
quantile_50 <- as.numeric(quantile(credit$AMT_INCOME_TOTAL)[3])
quantile_75 <- as.numeric(quantile(credit$AMT_INCOME_TOTAL)[4])


credit <- credit |>
  na.omit()
```

```{r}
head(credit)
```

```{r}
the_merged <- left_join(credit, bureau_grouped, by="SK_ID_CURR") %>%
  mutate(
    NUM_CREDITS = if_else(is.na(NUM_CREDITS), 0, NUM_CREDITS),
    MEAN_DAYS_CREDIT = if_else(is.na(MEAN_DAYS_CREDIT), 0, MEAN_DAYS_CREDIT),
    INCOME_TO_CREDIT = round(credit$AMT_INCOME_TOTAL / credit$AMT_CREDIT, 2),
    CREDIT_TO_NUM_CREDITS = round(NUM_CREDITS / credit$AMT_CREDIT, 2), 
    INCOME_TO_REGION = round(credit$AMT_INCOME_TOTAL / credit$REGION_POPULATION_RELATIVE, 2)
      )

the_merged <- as.data.frame(the_merged)

# move 'TARGET' back to the end
all_cols <- names(the_merged)
remaining_cols <- all_cols[all_cols != "TARGET"]
new_order <- c(remaining_cols, "TARGET")

# apply the new order to the data frame
merged_ordered <- the_merged[, new_order]
         
head(merged_ordered)
```

```{r}
# then, create sets
merged_fifty <- undersample_split(merged_ordered, 0.5)

splits_fifty <- strat_split(merged_fifty, target="TARGET", train_prop = 0.7, val_prop = 0.1, seed = 123)
train_strat_fifty <- splits_fifty$train
val_strat_fifty <- splits_fifty$val
test_strat_fifty <- splits_fifty$test

```

```{r}
# define model (used for all)
logit_mod <- logistic_reg() |>
  set_mode("classification") |>
  set_engine("glm")
```

```{r}
colnames(train_strat_fifty)
```

```{r}
lg_rec <- recipe(TARGET ~ ., data = train_strat_fifty) |>
  step_rm("SK_ID_CURR") |>
  step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("REGION_POPULATION_RELATIVE") |>
  step_rm("INCOME_TO_CREDIT") |>
  step_rm("CNT_CHILDREN") |>
  step_rm("INCOME_CLASS_FOURTH") |>
  step_rm("INCOME_CLASS_THIRD") |>
  step_rm("INCOME_CLASS_SECOND") |>
  step_rm("CODE_GENDER") |>
  # step_rm("FAMILY_STATUS_MARRIED") |>
  # step_rm("FAMILY_STATUS_OTHER") |>
  step_rm("CONTRACT_TYPE_REVOLVING") |>
  # step_rm("DAYS_EMPLOYED") |>
  # step_rm("INCOME_TO_REGION") |>
  # step_rm("CREDIT_TO_NUM_CREDITS") |>
  step_mutate(TARGET = factor(TARGET, levels=c(0, 1))) |>
  step_dummy(all_nominal_predictors())

logit_wkflow <- workflow() |>
  add_model(logit_mod) |>
  add_recipe(lg_rec)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
logit_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall, roc_auc)) |>
  collect_metrics()
```
```{r}
cross_validation(data = train_strat_fifty, model = "logistic", model_wkflow = logit_wkflow,
                 num_splits = 5, no_class = 0, bound = 0.5)
```

```{r}

splits <- random_split(merged_fifty, train_prop = 0.7, val_prop = 0.1, seed = 123)
train_strat <- splits$train
val_strat <- splits$val
test_strat <- splits$test

lg_rec <- recipe(TARGET ~ ., data = train_strat) |>
  step_rm("SK_ID_CURR") |>
   step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("REGION_POPULATION_RELATIVE") |>
  step_mutate(TARGET = factor(TARGET, levels=c(0, 1))) |>
  step_dummy(all_nominal_predictors())

logit_wkflow <- workflow() |>
  add_model(logit_mod) |>
  add_recipe(lg_rec)

set.seed(18938)
cvs <- vfold_cv(train_strat, v = 5)
# logit_wkflow |>
#   fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall, roc_auc)) |>
#   collect_metrics()

cross_validation(data = train_strat, model = "logistic", model_wkflow = logit_wkflow,
                 num_splits = 5, no_class = 0, bound = 0.505)

understand_predictions(data = train_strat, model = "logistic", model_wkflow = logit_wkflow,
                 num_splits = 5, bound = 0.505)
# data, model, model_wkflow, num_splits, bound)
```
## TRYING A 30/70 SPLIT (CAN WE JUSTIFY?)

```{r}
colnames(merged_ordered)
```

```{r}
# merged_fifty <- undersample_split(merged_ordered, 0.45)
splits <- strat_split(merged_ordered, target = "TARGET", train_prop = .6, val_prop = 0.2, seed = 123)
# undersample the training, not the val and test
train_strat <- undersample_split(splits$train, 0.5)
val_strat <- splits$val
test_strat <- splits$test

lg_rec <- recipe(TARGET ~ ., data = train_strat) |>
  step_rm("SK_ID_CURR") |>
  step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("REGION_POPULATION_RELATIVE") |>
  step_rm("INCOME_TO_CREDIT") |>
  step_rm("CNT_CHILDREN") |>
  step_rm("CONTRACT_TYPE_REVOLVING") |>
  step_rm("INCOME_CLASS_FOURTH") |>
  step_rm("INCOME_CLASS_THIRD") |>
  step_rm("INCOME_CLASS_SECOND") |>
  step_rm("CODE_GENDER") |>
  step_mutate(TARGET = factor(TARGET, levels=c(0, 1))) |>
  step_dummy(all_nominal_predictors())

logit_wkflow <- workflow() |>
  add_model(logit_mod) |>
  add_recipe(lg_rec)

cross_validation(data = train_strat, model = "logistic", model_wkflow = logit_wkflow,
                 num_splits = 5, no_class = 0, bound = 0.5)

l_fit <- logit_wkflow |>
  fit(train_strat) |>
  extract_fit_parsnip()

preds <- predict(l_fit, new_data = test_strat)$.pred_class

test_strat |>
  mutate(predictions = preds) |>
  precision(truth = TARGET, estimate = predictions)

test_strat |>
  mutate(predictions = preds) |>
  recall(truth = TARGET, estimate = predictions)
```
```{r}
test_strat$CODE_GENDER
test_strat$TARGET
```

```{r}
calc_fairness_metrics(test_strat$CODE_GENDER, as.numeric(as.character(test_strat$TARGET)), as.numeric(as.character(preds)), no_class = 0)
```

```{r}
cross_validation(data = val_strat, model = "logistic", model_wkflow = logit_wkflow,
                 num_splits = 5, no_class = 0, bound = 0.5)
```

```{r}
# define model (used for all)
lda_mod <- discrim_linear() |>
  set_mode("classification") |>
  set_engine("MASS")
```

```{r}
merged_ordered_test <- merged_ordered |>
  select(-c("SK_ID_CURR", "AMT_INCOME_TOTAL", "REGION_POPULATION_RELATIVE", "INCOME_TO_CREDIT", "CNT_CHILDREN",
            "CONTRACT_TYPE_REVOLVING", "INCOME_CLASS_FOURTH", "INCOME_CLASS_THIRD", "INCOME_CLASS_SECOND", "CODE_GENDER"))

# merged_fifty <- undersample_split(merged_ordered, 0.45)
splits <- strat_split(merged_ordered_test, target = "TARGET", train_prop = .6, val_prop = 0.2, seed = 123)
# undersample the training, not the val and test
train_strat <- undersample_split(splits$train, 0.5)
val_strat <- splits$val
test_strat <- splits$test

train_strat <- train_strat |>
  mutate(TARGET = if_else(TARGET == 0, -1, 1))

svc_rec <- recipe(TARGET ~ ., data = train_strat) |>
  #step_rm("SK_ID_CURR") |>
  # step_rm("AMT_INCOME_TOTAL") |> 
  # step_rm("REGION_POPULATION_RELATIVE") |>
  # step_rm("INCOME_TO_CREDIT") |>
  # step_rm("CNT_CHILDREN") |>
  # step_rm("CONTRACT_TYPE_REVOLVING") |>
  # step_rm("INCOME_CLASS_FOURTH") |>
  # step_rm("INCOME_CLASS_THIRD") |>
  # step_rm("INCOME_CLASS_SECOND") |>
  # step_rm("CODE_GENDER") |>
  step_mutate(TARGET = factor(TARGET, levels=c(-1, 1))) |>
  step_dummy(all_nominal_predictors())

svc_mod <- svm_linear() |>
  set_mode("classification") |>
  set_engine("LiblineaR")

svc_wkflow <- workflow() |>
  add_model(svc_mod) |>
  add_recipe(svc_rec)

train_strat_test <- train_strat |>
  select(-c("SK_ID_CURR", "AMT_INCOME_TOTAL", "REGION_POPULATION_RELATIVE", "INCOME_TO_CREDIT", "CNT_CHILDREN",
            "CONTRACT_TYPE_REVOLVING", "INCOME_CLASS_FOURTH", "INCOME_CLASS_THIRD", "INCOME_CLASS_SECOND", "CODE_GENDER"))

cross_validation(data = train_strat, model = "svc", model_wkflow = svc_wkflow,
                 num_splits = 5, no_class = -1, bound = 0.5)

l_fit <- logit_wkflow |>
  fit(train_strat) |>
  extract_fit_parsnip()

preds <- predict(l_fit, new_data = test_strat)$.pred_class

test_strat |>
  mutate(predictions = preds) |>
  precision(truth = TARGET, estimate = predictions)

test_strat |>
  mutate(predictions = preds) |>
  recall(truth = TARGET, estimate = predictions)
```

## Moving to the Test and Training Sets

