---
title: "svc"
output: html_document
date: "2025-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(dplyr)

source(here::here("data_cleaning.R"))
source(here::here("functions.R"))
source(here::here("splits.R"))
```


## SVC

just going to try some tidymodels SVC stuff to see what works and what I can 
come up with and whatnot

```{r}
# load the data
credit <- credit |>
  na.omit()

# then, create sets
splits <- random_split(credit, train_prop = 0.7, val_prop = 0.1, seed = 123)
train_random <- splits$train
val_random <- splits$validation
test_random <- splits$test
```


```{r}
# define model (used for all)
svm_mod <- svm_linear() |>
  set_mode("classification") |>
  set_engine("LiblineaR")
```

```{r}
# mutate target, c(1, -1) [because the target should come first]
train_random$TARGET <- ifelse(train_random$TARGET == 0, -1, 1)
```

```{r}
train_random$TARGET
```

```{r}
# fit *this* model
svc_reg <- recipe(TARGET ~ ., data = train_random) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors()) 
               
svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)
```


```{r}
# NOTE: THIS TAKES FOREVER!!
# NOTE: ALSO NO ROC!!!

# collect metrics (illegally)
set.seed(18938)
cvs <- vfold_cv(train_random, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```


```{r}
credit_fifty <- undersample_split(credit, 0.5)
head(credit_fifty)
```


```{r}
# fit *this* model
splits_fifty <- random_split(credit_fifty, train_prop = 0.7, val_prop = 0.1, seed = 123)

train_random_fifty <- splits_fifty$train
val_random_fifty <- splits_fifty$validation
test_random_fifty <- splits_fifty$test
train_random_fifty$TARGET <- ifelse(train_random_fifty$TARGET == 0, -1, 1)


svc_reg <- recipe(TARGET ~ CONTRACT_TYPE_REVOLVING + DOCUMENTS_FLAGGED + FLAG_OWN_REALTY, data = train_random_fifty) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors()) 
               
svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)
```

```{r}
set.seed(2222)
cvs <- vfold_cv(train_random_fifty, v = 5)

svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```
my next thought is to bring in the credit beuarua, join and include the number 
of credits and also average of days credit

want to be careful about NAs here ...