---
title: "SVC Classifier"
output: html_document
date: "2025-11-16"
---

**Fit and Evaluate SVC on Training Set**

```{r, include=FALSE}
source(here::here("scripts/libraries.R"))
source(here::here("scripts/data_cleaning.R"))
source(here::here("scripts/functions.R"))
source(here::here("scripts/splits.R"))
```

```{r}
# define model (used for all)
svm_mod <- svm_linear() |>
  set_mode("classification") |>
  set_engine("LiblineaR")
```

### Random Split, No UnderSampling

```{r}
# create train/val/test splits
splits <- random_split(df, train_prop = 0.6, val_prop = 0.2, seed = 123)
train_random <- splits$train
val_random <- splits$validation
test_random <- splits$test
```

```{r}
# mutate target, c(1, -1) [because the target should come first]
train_random$TARGET <- ifelse(train_random$TARGET == 0, -1, 1)
```

```{r}
svc_reg <- recipe(TARGET ~ ., data = train_random) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_rm(SK_ID_CURR, INCOME_TO_CREDIT, CREDIT_TO_NUM_CREDITS, INCOME_TO_REGION,
        CODE_GENDER, AGE_GROUPS) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors()) 
               
svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_random, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```


## Stratified Split, 50/50 Undersampling

```{r}
splits <- strat_split(df, target="TARGET", train_prop = 0.6, val_prop = 0.2, seed = 123)
train_strat_fifty <- undersample_split(splits$train)
val_strat_fifty <- splits$validation
test_strat_fifty <- splits$test

train_strat_fifty$TARGET <- ifelse(train_strat_fifty$TARGET == 0, -1, 1)
```

```{r}
svc_reg <- recipe(TARGET ~ ., data = train_strat_fifty) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_rm(SK_ID_CURR, INCOME_TO_CREDIT, CREDIT_TO_NUM_CREDITS, INCOME_TO_REGION,
        CODE_GENDER, AGE_GROUPS) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors()) 
               
svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ AMT_CREDIT + AMT_ANNUITY + AMT_INCOME_TOTAL, data = train_strat_fifty) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ CNT_CHILDREN, data = train_strat_fifty) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ ., data = train_strat_fifty) |>
  step_rm("SK_ID_CURR") |>
  step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("REGION_POPULATION_RELATIVE") |>
  step_rm("INCOME_TO_CREDIT") |>
  step_rm("CNT_CHILDREN") |>
  step_rm("CONTRACT_TYPE_REVOLVING") |>
  step_rm("INCOME_CLASS_FOURTH") |>
  step_rm("INCOME_CLASS_THIRD") |>
  step_rm("INCOME_CLASS_SECOND") |>
  step_rm("CODE_GENDER") |>
  step_rm("AGE_GROUPS") |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ CONTRACT_TYPE_REVOLVING + AMT_CREDIT + AMT_INCOME_TOTAL + HOUSING_TYPE_OWN, data = train_strat_fifty) |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_naomit(all_predictors()) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ ., data = train_strat_fifty) |>
  step_rm("SK_ID_CURR") |>
  step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("CONTRACT_TYPE_REVOLVING") |>
  step_rm("FLAG_OWN_CAR") |>
  step_rm("FLAG_OWN_REALTY") |>
  step_rm("INCOME_CLASS_FOURTH") |>
  step_rm("INCOME_CLASS_THIRD") |>
  step_rm("INCOME_CLASS_SECOND") |>
  step_rm("CODE_GENDER") |>
  step_rm("AGE_GROUPS") |>
  step_rm("DAYS_EMPLOYED") |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```

```{r}
svc_reg <- recipe(TARGET ~ ., data = train_strat_fifty) |>
  step_rm("SK_ID_CURR") |>
  step_rm("AMT_INCOME_TOTAL") |> 
  step_rm("REGION_POPULATION_RELATIVE") |>
  step_rm("INCOME_TO_CREDIT") |>
  step_rm("CNT_CHILDREN") |>
  step_rm("CONTRACT_TYPE_REVOLVING") |>
  step_rm("FAMILY_STATUS_MARRIED") |>
  step_rm("FAMILY_STATUS_SINGLE") |>
  step_rm("HOUSING_TYPE_OWN") |>
  step_rm("HOUSING_TYPE_PARENTS") |>
  step_rm("CODE_GENDER") |>
  step_rm("AGE_GROUPS") |>
  step_rm("DAYS_EMPLOYED") |>
  step_mutate(TARGET = factor(TARGET, levels = c(1, -1))) |>
  step_dummy(all_nominal_predictors())

svm_wkflow <- workflow() |>
  add_model(svm_mod) |>
  add_recipe(svc_reg)

set.seed(18938)
cvs <- vfold_cv(train_strat_fifty, v = 5)
svm_wkflow |>
  fit_resamples(resamples = cvs, metrics = metric_set(accuracy, f_meas, precision, recall)) |>
  collect_metrics()
```